Repository UMCCMAP/web, pull requests merged in 2023-08, with the labels that each got.

#15 [Design/update search page UI/#13] 카페 리뷰 UI 수정, 카페 추천 퍼블리싱
  index.html
  package.json
  src/App.jsx
  src/assets/images/book.svg
  src/assets/images/bread.svg
  src/assets/images/cake.svg
  src/assets/images/car.svg
  src/assets/images/close.svg
  src/assets/images/closeSearchbar.svg
  src/assets/images/cmapLogoB.svg
  src/assets/images/cmapLogoG.svg
  src/assets/images/cmapmark.svg
  src/assets/images/coffee.svg
  src/assets/images/home.svg
  src/assets/images/mountain.svg
  src/assets/images/openSearchbar.svg
  src/assets/images/pasta.svg
  src/assets/images/photo.svg
  src/assets/images/scope.svg
  src/components/CafeMap/CafeReview.jsx
  src/components/CafeMap/MapCafeDetail.jsx
  src/components/CafeMap/MapListBar.jsx
  src/components/CafeMap/MapNavbar.jsx
  src/components/CafeMap/MapReview/ReadReview.jsx
  src/components/CafeMap/MapReview/RegisterReview.jsx
  src/components/CafeMap/MapReview/ReviewModal.jsx
  src/components/CafeMap/MapReview/ReviewModal.style.js
  src/components/CafeMap/MapReview/SaveCafe.jsx
  src/components/CafeMap/MapReview/UpdateReview.jsx
  src/components/Map.jsx
  src/pages/RecommendCafe/RecommendCafePage.jsx
  src/pages/RecommendCafe/components/SelectThemeModal.jsx
  src/pages/SearchPage.jsx
  src/pages/SearchPage/SearchPage.jsx
  src/pages/SearchPage/SearchPage.module.css
  src/pages/SearchPage/components/DetailSearch.jsx
  src/pages/SearchPage/components/DetailSearch.module.css
  src/pages/SearchPage/components/Modal/RegisterReview.jsx
  src/pages/SearchPage/components/Modal/ReviewModal.style.js
  src/pages/SearchPage/components/Modal/SaveCafe.jsx
  src/pages/SearchPage/components/Modal/UpdateReview.jsx
  src/pages/SearchPage/components/SearchNavbar.jsx
  src/pages/SearchPage/components/SearchNavbar.module.css
  src/styles/Button.style.js
  src/styles/Modal.style.js
  vite.config.js
  yarn.lock
Labels: 퍼블리싱

#17 [Design/main page/#4] 메인페이지 퍼블리싱
  package-lock.json
  src/assets/CMAP.png
  src/assets/CMAPblack.png
  src/assets/HomepageIcon/BgImg.png
  src/assets/HomepageIcon/BluestarIcon.png
  src/assets/HomepageIcon/CommunityIcon.png
  src/assets/HomepageIcon/MainLogo.png
  src/assets/HomepageIcon/MapIcon.png
  src/assets/HomepageIcon/RedstarIcon.png
  src/assets/HomepageIcon/SearchLogo.png
  src/assets/IntroIcon/cafeimg.png
  src/assets/IntroIcon/ex5.png
  src/assets/LoginIcon/kakaoIcon.png
  src/assets/LoginIcon/naverIcon.png
  src/assets/ProfileIcon/UserProfileIcon.png
  src/assets/ProfileImg.png
  src/components/Footer.jsx
  src/components/Login.jsx
  src/components/Logo.jsx
  src/pages/Homepage/Homepage.css
  src/pages/Homepage/Homepage.jsx
  src/pages/Intropage.jsx
  src/pages/Loginpage.jsx
  src/pages/Myprofile/EditProfile.jsx
  src/pages/Myprofile/Myprofile.jsx
  src/pages/Myprofile/profile.css
  yarn.lock
Labels: 퍼블리싱

#21 [Feat/page router/#18] 페이지 라우터 적용
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/ErrorPage.jsx
  src/Root.jsx
  src/assets/icon/CMAP.svg
  src/components/CafeMap/MapNavbar.jsx
  src/components/Header.jsx
  src/pages/Board/BoardList.jsx
  src/pages/Board/BoardModify.jsx
  src/pages/Board/BoardView.jsx
  src/pages/Board/BoardWrite.jsx
  src/pages/Board/components/Footer.jsx
  src/pages/Homepage/Homepage.jsx
  src/pages/Intropage.jsx
  yarn.lock
Labels: 기능구현

#19 [Feat/board write/#12] 게시판 글쓰기 구현
  src/App.jsx
  src/pages/Board/BoardModify.jsx
  src/pages/Board/BoardWrite.jsx
  src/pages/Board/components/Editor.css
  src/pages/Board/components/Editor.jsx
  src/pages/Board/styles/BoardCU.style.js
  src/pages/dummy/Boards.js
  yarn.lock
Labels: 기능구현

#20 [Feat/search cafe/#16] 주변 카페 검색 기능 구현
  package.json
  src/App.jsx
  src/assets/images/add.svg
  src/assets/images/book.svg
  src/assets/images/bread.svg
  src/assets/images/cake.svg
  src/assets/images/car.svg
  src/assets/images/coffee.svg
  src/assets/images/home.svg
  src/assets/images/mountain.svg
  src/assets/images/pasta.svg
  src/assets/images/photo.svg
  src/assets/images/reviewstar.svg
  src/components/CafeMap/CafeReview.jsx
  src/components/CafeMap/MapCafeDetail.jsx
  src/components/CafeMap/MapListBar.jsx
  src/components/CafeMap/MapNavbar.jsx
  src/components/CafeMap/MapReview/ImgDragDrop.jsx
  src/components/CafeMap/MapReview/ReadReview.jsx
  src/components/CafeMap/MapReview/RegisterReview.jsx
  src/components/CafeMap/MapReview/ReviewModal.jsx
  src/components/CafeMap/MapReview/SaveCafe.jsx
  src/components/CafeMap/MapReview/UpdateReview.jsx
  src/components/CafeMap/MapReview/styles/ImgDragDrop.style.js
  src/components/CafeMap/MapReview/styles/ReadReview.style.js
  src/components/CafeMap/MapReview/styles/ReviewModal.style.js
  src/components/CafeMap/MapReview/styles/SaveCafe.style.js
  src/components/CafeMap/styles/CafeReview.style.js
  src/components/CafeMap/styles/MapCafeDetail.style.js
  src/components/CafeMap/styles/MapListBar.style.js
  src/components/CafeMap/styles/MapNavbar.style.js
  src/pages/Main.jsx
  src/pages/RecommendCafe/RecommendCafePage.jsx
  src/pages/RecommendCafe/components/SelectThemeModal.jsx
  src/pages/RecommendCafe/components/styles/SelectThemeModal.style.js
  src/pages/SearchPage.jsx
  src/pages/dummy/Search.js
  src/styles/Modal.style.js
  src/styles/Transition.style.js
  yarn.lock
Labels: 기능구현

#29 [Chore/docker setting/#22] 도커 세팅
  .dockerignore
  .gitignore
  Dockerfile.dev
  Dockerfile.prod
  src/components/Header.jsx
  src/pages/Homepage/Homepage.jsx
  src/pages/Intropage.jsx
  vite.config.js
Labels: 환경설정

#31 [Design/remaining page/#27] cmap모달창 및 리뷰작성창
  src/App.jsx
  src/assets/icon/Arrow.png
  src/assets/icon/CmapModalIcon/book.svg
  src/assets/icon/CmapModalIcon/bread.svg
  src/assets/icon/CmapModalIcon/brunch.svg
  src/assets/icon/CmapModalIcon/camera.svg
  src/assets/icon/CmapModalIcon/coffee.svg
  src/assets/icon/CmapModalIcon/desert.svg
  src/assets/icon/CmapModalIcon/parking.svg
  src/assets/icon/CmapModalIcon/view.svg
  src/pages/Board/BoardView.jsx
  src/pages/Board/dummy/BoardViewData.js
  src/pages/Board/styles/BoardCU.style.js
  src/pages/Board/styles/BoardViews.style.js
  src/pages/Cmap/CmapPage.jsx
  src/pages/Cmap/components/ListModal.jsx
  src/pages/Cmap/components/MapUserBar.jsx
  src/pages/Cmap/components/styles/ListModal.style.js
  src/pages/Cmap/components/styles/MapUserBar.style.js
  src/pages/CmapPage.jsx
Labels: 퍼블리싱

#33 [Feat/recommend cafe/#28] 이미지 slick, 테마 선택 기능 구현
  package.json
  src/assets/images/next.svg
  src/assets/images/prev.svg
  src/components/CafeMap/MapReview/ReadReview.jsx
  src/components/CafeMap/MapReview/styles/ReadReview.style.js
  src/pages/RecommendCafe/RecommendCafePage.jsx
  src/pages/RecommendCafe/components/SelectThemeModal.jsx
  src/pages/RecommendCafe/components/styles/SelectThemeModal.style.js
  yarn.lock
Labels: 기능구현

#45 [Feat/search map api/#34] 지도, 리뷰, 카페 저장, 로그인, 추천 api 적용
  package.json
  src/App.jsx
  src/apis/baseAxios.js
  src/components/CafeMap/CafeReview.jsx
  src/components/CafeMap/MapCafeDetail.jsx
  src/components/CafeMap/MapListBar.jsx
  src/components/CafeMap/MapNavbar.jsx
  src/components/CafeMap/MapReview/ImgDragDrop.jsx
  src/components/CafeMap/MapReview/ReadReview.jsx
  src/components/CafeMap/MapReview/RegisterReview.jsx
  src/components/CafeMap/MapReview/SaveCafe.jsx
  src/components/CafeMap/MapReview/UpdateReview.jsx
  src/components/CafeMap/styles/CafeReview.style.js
  src/components/CafeMap/styles/MapCafeDetail.style.js
  src/components/CafeMap/styles/MapNavbar.style.js
  src/components/Map.jsx
  src/components/access/PrivatePages.jsx
  src/components/access/PublicPages.jsx
  src/components/access/isLogin.js
  src/pages/Homepage/Homepage.jsx
  src/pages/Login/LoginCallbackPage.jsx
  src/pages/Login/Loginpage.jsx
  src/pages/Login/RegisterPage.jsx
  src/pages/RecommendCafe/RecommendCafePage.jsx
  src/pages/RecommendCafe/components/SelectThemeModal.jsx
  src/pages/RecommendCafe/components/styles/SelectThemeModal.style.js
  src/pages/SearchPage.jsx
  src/styles/Homepage.style.js
  src/styles/Loginpage.style.js
  yarn.lock
Labels: 기능구현

#42 [Feat/board write api/#32] 게시판 api 연동
  index.html
  src/App.jsx
  src/assets/icon/BoardReviewIcon.svg
  src/assets/icon/arrowBottom.svg
  src/assets/icon/reviewFillHeart.svg
  src/assets/icon/reviewHeart.svg
  src/components/Header.jsx
  src/pages/Board/BoardList.jsx
  src/pages/Board/BoardModify.jsx
  src/pages/Board/BoardView.jsx
  src/pages/Board/BoardWrite.jsx
  src/pages/Board/components/Editor.css
  src/pages/Board/components/Editor.jsx
  src/pages/Board/dummy/Boards.js
  src/pages/Board/styles/BoardCU.style.js
  src/pages/Board/styles/BoardList.style.js
  src/pages/Board/styles/BoardView.style.js
  src/pages/Board/styles/Common.style.js
  yarn.lock
Labels: 기능구현

#47 [Feat/cmap list/#43] cmap wantList
  src/App.jsx
  src/components/Map.jsx
  src/pages/Cmap/CmapPage.jsx
  src/pages/Cmap/components/ListModal.jsx
  src/pages/Cmap/components/MapUserBar.jsx
  src/pages/Cmap/components/styles/ListModal.style.js
  src/pages/Cmap/components/styles/MapUserBar.style.js
  src/pages/CmapPage.jsx
  src/pages/Homepage/Homepage.jsx
  src/pages/Myprofile/Myprofile.jsx
  src/pages/dummy/Token.js
Labels: 기능구현

#49 [Feat/search map api/#34] 지도 저장, 지도 검색 api 수정
  src/components/CafeMap/MapCafeDetail.jsx
  src/components/CafeMap/MapListBar.jsx
  src/components/CafeMap/MapNavbar.jsx
  src/components/CafeMap/MapReview/ReadReview.jsx
  src/components/CafeMap/MapReview/SaveCafe.jsx
  src/components/CafeMap/MapReview/styles/ReadReview.style.js
  src/components/CafeMap/styles/MapCafeDetail.style.js
  src/components/Map.jsx
  src/pages/SearchPage.jsx
Labels: 기능구현

#50 Feat/remaining page/#48
  src/App.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/pages/Board/BoardList.jsx
  src/pages/Board/BoardModify.jsx
  src/pages/Board/BoardView.jsx
  src/pages/Board/BoardWrite.jsx
  src/pages/Board/components/Editor.jsx
  src/pages/Board/dummy/BoardViewData.js
  src/pages/Board/styles/BoardView.style.js
  src/pages/CafeList.jsx
  src/pages/Cmap/CmapPage.jsx
  src/pages/Cmap/components/ListModal.jsx
  src/pages/Cmap/components/MapUserBar.jsx
  src/pages/IntroPage/Intropage.jsx
  src/pages/Myprofile/EditProfile.jsx
  src/pages/Myprofile/Myprofile.jsx
  src/pages/Myprofile/dummy/Follower.js
  src/pages/Myprofile/dummy/Profile.js
  src/pages/dummy/Boards.js
  src/pages/dummy/Search.js
  src/pages/dummy/Token.js
  src/styles/Homepage.style.js
  src/styles/Myprofilepage.style.js
Labels: 기능구현
